### ISSUE TITLE
Forum Navigation

### ISSUE THREAD

**Issue by anthonyfabius** [evearwen/BeeKeepr#8]
The Forum feature allows a user to interact with others via online forums. Right now we have no backend so this will be purely UI/UX. We want to showcase the flow of a user interacting with the forum by viewing and creating posts. Below are the specifications of the flow.

### Broad Forum Tab
When a user initially clicks on the Forum tab from the home page this is what they see. A bunch of topic tiles that specify the content of the posts within them.

For this tab to be finished all of the following must be ticked
- [ ] All the various forum topics
  - [ ] Clicking on them should lead to the specific forum tab
- [ ] UI/UX mostly adheres to current design

### Specific Forum Tab
When a user clicks on a tile to find post relating to a certain type of content all of those posts appear here. At this point the user can interact again to view a post or select the "New Post" button to create their own.

For this tab to be finished all of the following must be ticked
- [ ] A bunch of fake forum posts
  - [ ] Clicking on a post goes to the post viewing tab
- [ ] A new post button
  - [ ] Clicking on this goes to the post creation tab 
- [ ] UI/UX mostly adheres to current design

### Forum post viewing
This page appears when a user clicks on an existing post the contents post appear along with comments pertaining to it. This could be empty for now or filled with some random content

For this tab to be finished all of the following must be ticked
- [ ] UI/UX mostly adheres to current design

### Forum post creation 
This page appears when a when a user clicks on "New Post" in the specific forum tab. 

For this tab to be finished all of the following must be ticked
- [ ] Textbox for post content
- [ ] Buttons for posting
- [ ] UI/UX mostly adheres to current design

Current Designs
<p>
<img src="https://github.com/user-attachments/assets/43b86ddf-f95a-4105-88a6-d09581061d32" height=300 title="Broad Forum Tab">
<img src="https://github.com/user-attachments/assets/9e2ca1f0-1b45-410f-a38b-e878c77fd5ca" height=300 title="Specific Forum Tab">
<img src="https://github.com/user-attachments/assets/21dde5ee-8748-40b2-ad8d-9ac454758995" height=300 title="Forum post viewing tab">
<img src="https://github.com/user-attachments/assets/c7ef1ac8-24fc-4116-8a8f-6ff155f48c67" height=300 title="Forum post creation tab">
</p>

**Comment by sirpop3** [comment]
Dropped Feature
